/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type CaseStudies = {
  _type: 'caseStudies';
  caseStudies: number;
  orderRank: 'latest' | 'random';
};

export type GoogleReviews = {
  _type: 'googleReviews';
  reviews: number;
};

export type InfoTable = {
  _type: 'infoTable';
  title?: string;
  description?: string;
  firstRowHeader?: boolean;
  infoTable: Table;
};

export type VideoEmbed = {
  _type: 'videoEmbed';
  video?: YoutubeVideo;
  autoplay?: boolean;
  controls?: boolean;
};

export type RawHtml = {
  _type: 'rawHtml';
  rawHtml: string;
  centered?: boolean;
};

export type VerticalTabsItem = {
  _type: 'verticalTabsItem';
  title: string;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote' | 'hardBreak';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type VerticalTabs = {
  _type: 'verticalTabs';
  tabs: Array<
    {
      _key: string;
    } & VerticalTabsItem
  >;
};

export type TwoSlotRichTextImage = {
  _type: 'twoSlotRichTextImage';
  leftSlotType: 'richText' | 'image';
  leftRichText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  leftImage?: {
    id?: string;
    url?: string;
    alt_text?: string;
  };
  leftImageCaption?: string;
  leftImageAttribution?: string;
  rightSlotType: 'richText' | 'image';
  rightRichText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  rightImage?: {
    id?: string;
    url?: string;
    alt_text?: string;
  };
  rightImageCaption?: string;
  rightImageAttribution?: string;
};

export type TwoColumnRichTextAndForm = {
  _type: 'twoColumnRichTextAndForm';
  richText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote' | 'hardBreak';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  formHeading?: string;
  rentalSpaceReference: string;
  swapSides?: boolean;
};

export type TwoColumnRichTextAndImage = {
  _type: 'twoColumnRichTextAndImage';
  richText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote' | 'hardBreak';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  image?: {
    id?: string;
    url?: string;
    alt_text?: string;
  };
  swapSides?: boolean;
};

export type TwoColumnRichText = {
  _type: 'twoColumnRichText';
  richText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote' | 'hardBreak';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type TwoColumnList = {
  _type: 'twoColumnList';
  title?: string;
  items: Array<string>;
  showBackground?: boolean;
};

export type TwoCardSection = {
  _type: 'twoCardSection';
  cards: Array<
    {
      _key: string;
    } & ContentCard
  >;
};

export type Spacer = {
  _type: 'spacer';
  size: 'spacer-small' | 'spacer-medium' | 'spacer-large';
};

export type SocialMediaAccount = {
  _type: 'socialMediaAccount';
  label: 'Facebook' | 'Twitter' | 'Instagram' | 'LinkedIn' | 'X';
  href: string;
};

export type RailwayArches = {
  _id: string;
  _type: 'railwayArches';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  metadata?: Metadata;
  title: string;
  heroImage?: BrandfolderImage;
  content?: Array<
    | ({
        _key: string;
      } & PlainText)
    | ({
        _key: string;
      } & RichText)
    | ({
        _key: string;
      } & CtaRichText)
    | ({
        _key: string;
      } & TwoColumnRichText)
    | ({
        _key: string;
      } & TwoCardSection)
    | ({
        _key: string;
      } & ThreeCardSection)
    | ({
        _key: string;
      } & FourCardSection)
    | ({
        _key: string;
      } & ImageRow)
    | ({
        _key: string;
      } & HorizontalContentCard)
    | ({
        _key: string;
      } & TwoColumnList)
    | ({
        _key: string;
      } & TwoColumnRichTextAndImage)
    | ({
        _key: string;
      } & TwoColumnRichTextAndForm)
    | ({
        _key: string;
      } & TwoSlotRichTextImage)
    | ({
        _key: string;
      } & FullWidthImage)
    | ({
        _key: string;
      } & VerticalTabs)
    | ({
        _key: string;
      } & PdfDownload)
    | ({
        _key: string;
      } & Spacer)
    | ({
        _key: string;
      } & RawHtml)
    | ({
        _key: string;
      } & VideoEmbed)
    | ({
        _key: string;
      } & InfoTable)
    | ({
        _key: string;
      } & GoogleReviews)
    | ({
        _key: string;
      } & CaseStudies)
  >;
  featuredProperties?: FeaturedProperties;
};

export type PropertyDetails = {
  _id: string;
  _type: 'propertyDetails';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  terms?: string;
  why_us?: string;
  reasons_list?: {
    reason1_title?: string;
    reason1_description?: string;
    reason2_title?: string;
    reason2_description?: string;
    reason3_title?: string;
    reason3_description?: string;
  };
};

export type PropertiesCta = {
  _id: string;
  _type: 'propertiesCta';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  content: string;
  ctaLink: string;
};

export type PlainText = {
  _type: 'plainText';
  title: string;
  body?: string;
};

export type PdfDownload = {
  _type: 'pdfDownload';
  pdf?: {
    text?: string;
    href: string;
  };
};

export type BlogArticle = {
  _id: string;
  _type: 'blogArticle';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  metadata?: Metadata;
  title: string;
  slug: Slug;
  date: string;
  author?: string;
  heroImage?: BrandfolderImage;
  summary: string;
  linkText?: string;
  content: Array<
    | ({
        _key: string;
      } & PlainText)
    | ({
        _key: string;
      } & RichText)
    | ({
        _key: string;
      } & CtaRichText)
    | ({
        _key: string;
      } & TwoColumnRichText)
    | ({
        _key: string;
      } & TwoCardSection)
    | ({
        _key: string;
      } & ThreeCardSection)
    | ({
        _key: string;
      } & FourCardSection)
    | ({
        _key: string;
      } & ImageRow)
    | ({
        _key: string;
      } & HorizontalContentCard)
    | ({
        _key: string;
      } & TwoColumnList)
    | ({
        _key: string;
      } & TwoColumnRichTextAndImage)
    | ({
        _key: string;
      } & TwoColumnRichTextAndForm)
    | ({
        _key: string;
      } & TwoSlotRichTextImage)
    | ({
        _key: string;
      } & FullWidthImage)
    | ({
        _key: string;
      } & VerticalTabs)
    | ({
        _key: string;
      } & PdfDownload)
    | ({
        _key: string;
      } & Spacer)
    | ({
        _key: string;
      } & RawHtml)
    | ({
        _key: string;
      } & VideoEmbed)
    | ({
        _key: string;
      } & InfoTable)
    | ({
        _key: string;
      } & GoogleReviews)
    | ({
        _key: string;
      } & CaseStudies)
  >;
  sideContent?: Array<
    | ({
        _key: string;
      } & ContentCard)
    | ({
        _key: string;
      } & RichText)
    | ({
        _key: string;
      } & LinkList)
  >;
};

export type NewsArticle = {
  _id: string;
  _type: 'newsArticle';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  metadata?: Metadata;
  title: string;
  slug: Slug;
  date: string;
  articleType?: 'news' | 'report';
  author?: string;
  heroImage?: BrandfolderImage;
  summary: string;
  linkText?: string;
  content: Array<
    | ({
        _key: string;
      } & PlainText)
    | ({
        _key: string;
      } & RichText)
    | ({
        _key: string;
      } & CtaRichText)
    | ({
        _key: string;
      } & TwoColumnRichText)
    | ({
        _key: string;
      } & TwoCardSection)
    | ({
        _key: string;
      } & ThreeCardSection)
    | ({
        _key: string;
      } & FourCardSection)
    | ({
        _key: string;
      } & ImageRow)
    | ({
        _key: string;
      } & HorizontalContentCard)
    | ({
        _key: string;
      } & TwoColumnList)
    | ({
        _key: string;
      } & TwoColumnRichTextAndImage)
    | ({
        _key: string;
      } & TwoColumnRichTextAndForm)
    | ({
        _key: string;
      } & TwoSlotRichTextImage)
    | ({
        _key: string;
      } & FullWidthImage)
    | ({
        _key: string;
      } & VerticalTabs)
    | ({
        _key: string;
      } & PdfDownload)
    | ({
        _key: string;
      } & Spacer)
    | ({
        _key: string;
      } & RawHtml)
    | ({
        _key: string;
      } & VideoEmbed)
    | ({
        _key: string;
      } & InfoTable)
    | ({
        _key: string;
      } & GoogleReviews)
    | ({
        _key: string;
      } & CaseStudies)
  >;
  sideContent?: Array<
    | ({
        _key: string;
      } & ContentCard)
    | ({
        _key: string;
      } & RichText)
    | ({
        _key: string;
      } & LinkList)
  >;
};

export type NavigationItem = {
  _type: 'navigationItem';
  label?: string;
  href: string;
  subnav?: Array<
    {
      _key: string;
    } & NavigationItem
  >;
};

export type Navigation = {
  _id: string;
  _type: 'navigation';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  findYourSpace?: Array<
    {
      _key: string;
    } & NavigationItem
  >;
  featuredLocations?: Array<
    {
      _key: string;
    } & NavigationItem
  >;
  whyUs?: Array<
    {
      _key: string;
    } & NavigationItem
  >;
  existingCustomers?: Array<
    {
      _key: string;
    } & NavigationItem
  >;
  aboutUs?: Array<
    {
      _key: string;
    } & NavigationItem
  >;
};

export type LinkList = {
  _type: 'linkList';
  title?: string;
  items: Array<{
    title: string;
    url: string;
    _key: string;
  }>;
};

export type IndexHeroes = {
  _id: string;
  _type: 'indexHeroes';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  indexHeroImages?: {
    featuredLocations?: BrandfolderImage;
    findYourSpace?: BrandfolderImage;
    newsAndReports?: BrandfolderImage;
    caseStudies?: BrandfolderImage;
  };
};

export type ImageRow = {
  _type: 'imageRow';
  image?: {
    id?: string;
    url?: string;
    alt_text?: string;
  };
  title: string;
  content?: string;
  ctaText: string;
  ctaUrl: string;
  ctaColour?: 'navy' | 'teal' | 'orange' | 'white';
  ctaIcon?: 'phone' | 'email' | 'search';
  cta2text?: string;
  cta2url?: string;
  cta2colour?: 'navy' | 'teal' | 'orange' | 'white';
  cta2icon?: 'phone' | 'email' | 'search';
  dark?: boolean;
  overlayText: boolean;
};

export type HorizontalContentCardSection = {
  _type: 'horizontalContentCardSection';
  cards?: Array<
    {
      _key: string;
    } & HorizontalContentCard
  >;
};

export type HorizontalContentCard = {
  _type: 'horizontalContentCard';
  image?: {
    id?: string;
    url?: string;
  };
  title: string;
  contentType?: 'text' | 'block';
  content?: string;
  richText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote' | 'hardBreak';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  ctaType?: 'link' | 'button' | 'clickable' | 'none';
  linkText?: string;
  linkUrl?: string;
  swapSides?: boolean;
};

export type Hero = {
  _type: 'hero';
  title?: string;
  description?: string;
  backgroundImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Globals = {
  _id: string;
  _type: 'globals';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  footerLinks?: Array<
    {
      _key: string;
    } & FooterLink
  >;
  socialMedia?: Array<
    {
      _key: string;
    } & SocialMediaAccount
  >;
};

export type GeneralInformation = {
  _id: string;
  _type: 'generalInformation';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  metadata?: Metadata;
  title: string;
  slug: Slug;
  parent?:
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'genericPage';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'homepage';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'featuredLocations';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'existingCustomers';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'landingPage';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'featuredLocationsSub';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'findYourSpace';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'generalInformation';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'twoColumnEditorial';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'aboutUs';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'whyUs';
      };
  content?: Array<
    | ({
        _key: string;
      } & PlainText)
    | ({
        _key: string;
      } & RichText)
    | ({
        _key: string;
      } & CtaRichText)
    | ({
        _key: string;
      } & TwoColumnRichText)
    | ({
        _key: string;
      } & TwoCardSection)
    | ({
        _key: string;
      } & ThreeCardSection)
    | ({
        _key: string;
      } & FourCardSection)
    | ({
        _key: string;
      } & ImageRow)
    | ({
        _key: string;
      } & HorizontalContentCard)
    | ({
        _key: string;
      } & TwoColumnList)
    | ({
        _key: string;
      } & TwoColumnRichTextAndImage)
    | ({
        _key: string;
      } & TwoColumnRichTextAndForm)
    | ({
        _key: string;
      } & TwoSlotRichTextImage)
    | ({
        _key: string;
      } & FullWidthImage)
    | ({
        _key: string;
      } & VerticalTabs)
    | ({
        _key: string;
      } & PdfDownload)
    | ({
        _key: string;
      } & Spacer)
    | ({
        _key: string;
      } & RawHtml)
    | ({
        _key: string;
      } & VideoEmbed)
    | ({
        _key: string;
      } & InfoTable)
    | ({
        _key: string;
      } & GoogleReviews)
    | ({
        _key: string;
      } & CaseStudies)
  >;
};

export type GenericPage = {
  _id: string;
  _type: 'genericPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  metadata?: Metadata;
  title: string;
  slug: Slug;
  parent?:
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'genericPage';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'homepage';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'featuredLocations';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'existingCustomers';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'landingPage';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'featuredLocationsSub';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'findYourSpace';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'generalInformation';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'twoColumnEditorial';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'aboutUs';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'whyUs';
      };
};

export type LandingPage = {
  _id: string;
  _type: 'landingPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  metadata?: Metadata;
  title: string;
  slug: Slug;
  parent?:
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'genericPage';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'homepage';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'featuredLocations';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'existingCustomers';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'landingPage';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'featuredLocationsSub';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'findYourSpace';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'generalInformation';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'twoColumnEditorial';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'aboutUs';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'whyUs';
      };
  pageIntroText: string;
  heroImage?: BrandfolderImage;
  content?: Array<
    | ({
        _key: string;
      } & PlainText)
    | ({
        _key: string;
      } & RichText)
    | ({
        _key: string;
      } & CtaRichText)
    | ({
        _key: string;
      } & TwoColumnRichText)
    | ({
        _key: string;
      } & TwoCardSection)
    | ({
        _key: string;
      } & ThreeCardSection)
    | ({
        _key: string;
      } & FourCardSection)
    | ({
        _key: string;
      } & ImageRow)
    | ({
        _key: string;
      } & HorizontalContentCard)
    | ({
        _key: string;
      } & TwoColumnList)
    | ({
        _key: string;
      } & TwoColumnRichTextAndImage)
    | ({
        _key: string;
      } & TwoColumnRichTextAndForm)
    | ({
        _key: string;
      } & TwoSlotRichTextImage)
    | ({
        _key: string;
      } & FullWidthImage)
    | ({
        _key: string;
      } & VerticalTabs)
    | ({
        _key: string;
      } & PdfDownload)
    | ({
        _key: string;
      } & Spacer)
    | ({
        _key: string;
      } & RawHtml)
    | ({
        _key: string;
      } & VideoEmbed)
    | ({
        _key: string;
      } & InfoTable)
    | ({
        _key: string;
      } & GoogleReviews)
    | ({
        _key: string;
      } & CaseStudies)
  >;
};

export type TwoColumnEditorial = {
  _id: string;
  _type: 'twoColumnEditorial';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  metadata?: Metadata;
  title: string;
  slug: Slug;
  parent?:
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'genericPage';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'homepage';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'featuredLocations';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'existingCustomers';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'landingPage';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'featuredLocationsSub';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'findYourSpace';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'generalInformation';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'twoColumnEditorial';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'aboutUs';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'whyUs';
      };
  heroImage?: BrandfolderImage;
  content?: Array<
    | ({
        _key: string;
      } & PlainText)
    | ({
        _key: string;
      } & RichText)
    | ({
        _key: string;
      } & CtaRichText)
    | ({
        _key: string;
      } & TwoColumnRichText)
    | ({
        _key: string;
      } & TwoCardSection)
    | ({
        _key: string;
      } & ThreeCardSection)
    | ({
        _key: string;
      } & FourCardSection)
    | ({
        _key: string;
      } & ImageRow)
    | ({
        _key: string;
      } & HorizontalContentCard)
    | ({
        _key: string;
      } & TwoColumnList)
    | ({
        _key: string;
      } & TwoColumnRichTextAndImage)
    | ({
        _key: string;
      } & TwoColumnRichTextAndForm)
    | ({
        _key: string;
      } & TwoSlotRichTextImage)
    | ({
        _key: string;
      } & FullWidthImage)
    | ({
        _key: string;
      } & VerticalTabs)
    | ({
        _key: string;
      } & PdfDownload)
    | ({
        _key: string;
      } & Spacer)
    | ({
        _key: string;
      } & RawHtml)
    | ({
        _key: string;
      } & VideoEmbed)
    | ({
        _key: string;
      } & InfoTable)
    | ({
        _key: string;
      } & GoogleReviews)
    | ({
        _key: string;
      } & CaseStudies)
  >;
  sideContent?: Array<
    | ({
        _key: string;
      } & ContentCard)
    | ({
        _key: string;
      } & RichText)
    | ({
        _key: string;
      } & LinkList)
  >;
};

export type WhyUs = {
  _id: string;
  _type: 'whyUs';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  metadata?: Metadata;
  title: string;
  pageIntroText: string;
  heroImage?: BrandfolderImage;
  content?: Array<
    | ({
        _key: string;
      } & PlainText)
    | ({
        _key: string;
      } & RichText)
    | ({
        _key: string;
      } & CtaRichText)
    | ({
        _key: string;
      } & TwoColumnRichText)
    | ({
        _key: string;
      } & TwoCardSection)
    | ({
        _key: string;
      } & ThreeCardSection)
    | ({
        _key: string;
      } & FourCardSection)
    | ({
        _key: string;
      } & ImageRow)
    | ({
        _key: string;
      } & HorizontalContentCard)
    | ({
        _key: string;
      } & TwoColumnList)
    | ({
        _key: string;
      } & TwoColumnRichTextAndImage)
    | ({
        _key: string;
      } & TwoColumnRichTextAndForm)
    | ({
        _key: string;
      } & TwoSlotRichTextImage)
    | ({
        _key: string;
      } & FullWidthImage)
    | ({
        _key: string;
      } & VerticalTabs)
    | ({
        _key: string;
      } & PdfDownload)
    | ({
        _key: string;
      } & Spacer)
    | ({
        _key: string;
      } & RawHtml)
    | ({
        _key: string;
      } & VideoEmbed)
    | ({
        _key: string;
      } & InfoTable)
    | ({
        _key: string;
      } & GoogleReviews)
    | ({
        _key: string;
      } & CaseStudies)
  >;
};

export type Homepage = {
  _id: string;
  _type: 'homepage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  metadata?: Metadata;
  title: string;
  pageIntroText: string;
  heroImage?: BrandfolderImage;
  videoUrl?: string;
  contentCards?: ThreeCardSection;
  textSection: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  content?: Array<
    | ({
        _key: string;
      } & PlainText)
    | ({
        _key: string;
      } & RichText)
    | ({
        _key: string;
      } & CtaRichText)
    | ({
        _key: string;
      } & TwoColumnRichText)
    | ({
        _key: string;
      } & TwoCardSection)
    | ({
        _key: string;
      } & ThreeCardSection)
    | ({
        _key: string;
      } & FourCardSection)
    | ({
        _key: string;
      } & ImageRow)
    | ({
        _key: string;
      } & HorizontalContentCard)
    | ({
        _key: string;
      } & TwoColumnList)
    | ({
        _key: string;
      } & TwoColumnRichTextAndImage)
    | ({
        _key: string;
      } & TwoColumnRichTextAndForm)
    | ({
        _key: string;
      } & TwoSlotRichTextImage)
    | ({
        _key: string;
      } & FullWidthImage)
    | ({
        _key: string;
      } & VerticalTabs)
    | ({
        _key: string;
      } & PdfDownload)
    | ({
        _key: string;
      } & Spacer)
    | ({
        _key: string;
      } & RawHtml)
    | ({
        _key: string;
      } & VideoEmbed)
    | ({
        _key: string;
      } & InfoTable)
    | ({
        _key: string;
      } & GoogleReviews)
    | ({
        _key: string;
      } & CaseStudies)
  >;
};

export type ThreeCardSection = {
  _type: 'threeCardSection';
  cards: Array<
    {
      _key: string;
    } & ContentCard
  >;
};

export type FullWidthImage = {
  _type: 'fullWidthImage';
  image?: {
    id?: string;
    url?: string;
    alt_text?: string;
  };
  fullHeight?: boolean;
};

export type FourCardSection = {
  _type: 'fourCardSection';
  cards: Array<
    {
      _key: string;
    } & ContentCard
  >;
};

export type FooterLink = {
  _type: 'footerLink';
  label: string;
  href: string;
};

export type Footer = {
  _type: 'footer';
  featuredLinks?: Array<
    {
      _key: string;
    } & FooterLink
  >;
};

export type FindYourSpace = {
  _id: string;
  _type: 'findYourSpace';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  metadata?: Metadata;
  title: string;
  slug: Slug;
  heroImage?: BrandfolderImage;
  summary: string;
  linkText?: string;
  pageIntroText: RichText;
  pageIntroCTATitle: string;
  pageIntroCTADescription: string;
  pageIntroCTALinkText: string;
  pageIntroCTALinkUrl: string;
  content: Array<
    | ({
        _key: string;
      } & PlainText)
    | ({
        _key: string;
      } & RichText)
    | ({
        _key: string;
      } & CtaRichText)
    | ({
        _key: string;
      } & TwoColumnRichText)
    | ({
        _key: string;
      } & TwoCardSection)
    | ({
        _key: string;
      } & ThreeCardSection)
    | ({
        _key: string;
      } & FourCardSection)
    | ({
        _key: string;
      } & ImageRow)
    | ({
        _key: string;
      } & HorizontalContentCard)
    | ({
        _key: string;
      } & TwoColumnList)
    | ({
        _key: string;
      } & TwoColumnRichTextAndImage)
    | ({
        _key: string;
      } & TwoColumnRichTextAndForm)
    | ({
        _key: string;
      } & TwoSlotRichTextImage)
    | ({
        _key: string;
      } & FullWidthImage)
    | ({
        _key: string;
      } & VerticalTabs)
    | ({
        _key: string;
      } & PdfDownload)
    | ({
        _key: string;
      } & Spacer)
    | ({
        _key: string;
      } & RawHtml)
    | ({
        _key: string;
      } & VideoEmbed)
    | ({
        _key: string;
      } & InfoTable)
    | ({
        _key: string;
      } & GoogleReviews)
    | ({
        _key: string;
      } & CaseStudies)
  >;
  sideContent?: Array<
    | ({
        _key: string;
      } & ContentCard)
    | ({
        _key: string;
      } & RichText)
    | ({
        _key: string;
      } & LinkList)
  >;
  featuredProperties?: FeaturedProperties;
  orderRank?: string;
};

export type FeaturedLocationsSub = {
  _id: string;
  _type: 'featuredLocationsSub';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  metadata?: Metadata;
  title: string;
  slug: Slug;
  parentLocation?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'featuredLocations';
  };
  pageIntroText: string;
  heroImage?: BrandfolderImage;
  textArea: RichText;
  contactUsCTATitle: string;
  contactUsCTADescription: string;
  featuredProperties?: FeaturedProperties;
  content?: Array<
    | ({
        _key: string;
      } & PlainText)
    | ({
        _key: string;
      } & RichText)
    | ({
        _key: string;
      } & CtaRichText)
    | ({
        _key: string;
      } & TwoColumnRichText)
    | ({
        _key: string;
      } & TwoCardSection)
    | ({
        _key: string;
      } & ThreeCardSection)
    | ({
        _key: string;
      } & FourCardSection)
    | ({
        _key: string;
      } & ImageRow)
    | ({
        _key: string;
      } & HorizontalContentCard)
    | ({
        _key: string;
      } & TwoColumnList)
    | ({
        _key: string;
      } & TwoColumnRichTextAndImage)
    | ({
        _key: string;
      } & TwoColumnRichTextAndForm)
    | ({
        _key: string;
      } & TwoSlotRichTextImage)
    | ({
        _key: string;
      } & FullWidthImage)
    | ({
        _key: string;
      } & VerticalTabs)
    | ({
        _key: string;
      } & PdfDownload)
    | ({
        _key: string;
      } & Spacer)
    | ({
        _key: string;
      } & RawHtml)
    | ({
        _key: string;
      } & VideoEmbed)
    | ({
        _key: string;
      } & InfoTable)
    | ({
        _key: string;
      } & GoogleReviews)
    | ({
        _key: string;
      } & CaseStudies)
  >;
};

export type FeaturedLocations = {
  _id: string;
  _type: 'featuredLocations';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  metadata?: Metadata;
  title: string;
  slug: Slug;
  keystoneSearchTerm: string;
  radius?: number;
  textArea: RichText;
  contactUsCTATitle: string;
  contactUsCTADescription: string;
  featuredProperties?: FeaturedProperties;
  locationImage?: BrandfolderImage;
  contentCardHeading?: string;
  contentCards: Array<
    {
      _key: string;
    } & ContentCard
  >;
  contentCardsLocation?: 'before-content' | 'after-content';
  composableContentHeading?: string;
  content?: Array<
    | ({
        _key: string;
      } & PlainText)
    | ({
        _key: string;
      } & RichText)
    | ({
        _key: string;
      } & CtaRichText)
    | ({
        _key: string;
      } & TwoColumnRichText)
    | ({
        _key: string;
      } & TwoCardSection)
    | ({
        _key: string;
      } & ThreeCardSection)
    | ({
        _key: string;
      } & FourCardSection)
    | ({
        _key: string;
      } & ImageRow)
    | ({
        _key: string;
      } & HorizontalContentCard)
    | ({
        _key: string;
      } & TwoColumnList)
    | ({
        _key: string;
      } & TwoColumnRichTextAndImage)
    | ({
        _key: string;
      } & TwoColumnRichTextAndForm)
    | ({
        _key: string;
      } & TwoSlotRichTextImage)
    | ({
        _key: string;
      } & FullWidthImage)
    | ({
        _key: string;
      } & VerticalTabs)
    | ({
        _key: string;
      } & PdfDownload)
    | ({
        _key: string;
      } & Spacer)
    | ({
        _key: string;
      } & RawHtml)
    | ({
        _key: string;
      } & VideoEmbed)
    | ({
        _key: string;
      } & InfoTable)
    | ({
        _key: string;
      } & GoogleReviews)
    | ({
        _key: string;
      } & CaseStudies)
  >;
  cardSummary: string;
  orderRank?: string;
};

export type FeaturedProperties = {
  _type: 'featuredProperties';
  title?: string;
  properties?: Array<string>;
};

export type ExistingCustomers = {
  _id: string;
  _type: 'existingCustomers';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  metadata?: Metadata;
  title: string;
  pageIntroText: string;
  heroImage?: BrandfolderImage;
  content?: Array<
    | ({
        _key: string;
      } & PlainText)
    | ({
        _key: string;
      } & RichText)
    | ({
        _key: string;
      } & CtaRichText)
    | ({
        _key: string;
      } & TwoColumnRichText)
    | ({
        _key: string;
      } & TwoCardSection)
    | ({
        _key: string;
      } & ThreeCardSection)
    | ({
        _key: string;
      } & FourCardSection)
    | ({
        _key: string;
      } & ImageRow)
    | ({
        _key: string;
      } & HorizontalContentCard)
    | ({
        _key: string;
      } & TwoColumnList)
    | ({
        _key: string;
      } & TwoColumnRichTextAndImage)
    | ({
        _key: string;
      } & TwoColumnRichTextAndForm)
    | ({
        _key: string;
      } & TwoSlotRichTextImage)
    | ({
        _key: string;
      } & FullWidthImage)
    | ({
        _key: string;
      } & VerticalTabs)
    | ({
        _key: string;
      } & PdfDownload)
    | ({
        _key: string;
      } & Spacer)
    | ({
        _key: string;
      } & RawHtml)
    | ({
        _key: string;
      } & VideoEmbed)
    | ({
        _key: string;
      } & InfoTable)
    | ({
        _key: string;
      } & GoogleReviews)
    | ({
        _key: string;
      } & CaseStudies)
  >;
};

export type Errors = {
  _id: string;
  _type: 'errors';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  errors?: {
    fourohfour?: string;
    fivehundred?: string;
    fourhundred?: string;
    property?: string;
  };
};

export type ContentCard = {
  _type: 'contentCard';
  image?: {
    id?: string;
    url?: string;
    alt_text?: string;
  };
  isFeatured?: boolean;
  title: string;
  contentType?: 'text' | 'block';
  content?: string;
  richText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote' | 'hardBreak';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  ctaType?: 'link' | 'button' | 'clickable' | 'none';
  linkText?: string;
  linkUrl?: string;
  cta2Type?: 'link' | 'button';
  link2Text?: string;
  link2Url?: string;
};

export type CtaRichText = {
  _type: 'ctaRichText';
  pageIntroText: RichText;
  pageIntroCTATitle: string;
  pageIntroCTADescription: string;
  pageIntroCTALinkText: string;
  pageIntroCTALinkUrl: string;
};

export type RichText = {
  _type: 'richText';
  richText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote' | 'hardBreak';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  centered?: boolean;
};

export type ComposableContent = Array<
  | ({
      _key: string;
    } & PlainText)
  | ({
      _key: string;
    } & RichText)
  | ({
      _key: string;
    } & CtaRichText)
  | ({
      _key: string;
    } & TwoColumnRichText)
  | ({
      _key: string;
    } & TwoCardSection)
  | ({
      _key: string;
    } & ThreeCardSection)
  | ({
      _key: string;
    } & FourCardSection)
  | ({
      _key: string;
    } & ImageRow)
  | ({
      _key: string;
    } & HorizontalContentCard)
  | ({
      _key: string;
    } & TwoColumnList)
  | ({
      _key: string;
    } & TwoColumnRichTextAndImage)
  | ({
      _key: string;
    } & TwoColumnRichTextAndForm)
  | ({
      _key: string;
    } & TwoSlotRichTextImage)
  | ({
      _key: string;
    } & FullWidthImage)
  | ({
      _key: string;
    } & VerticalTabs)
  | ({
      _key: string;
    } & PdfDownload)
  | ({
      _key: string;
    } & Spacer)
  | ({
      _key: string;
    } & RawHtml)
  | ({
      _key: string;
    } & VideoEmbed)
  | ({
      _key: string;
    } & InfoTable)
  | ({
      _key: string;
    } & GoogleReviews)
  | ({
      _key: string;
    } & CaseStudies)
>;

export type CaseStudy = {
  _id: string;
  _type: 'caseStudy';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  metadata?: Metadata;
  title: string;
  slug: Slug;
  date: string;
  heroImage?: BrandfolderImage;
  summary: string;
  linkText?: string;
  content: ComposableContent;
  sideContent?: Array<
    | ({
        _key: string;
      } & ContentCard)
    | ({
        _key: string;
      } & RichText)
    | ({
        _key: string;
      } & LinkList)
  >;
  orderRank?: string;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type BrandfolderPdf = {
  _type: 'brandfolderPdf';
  id?: string;
  url?: string;
};

export type AboutUs = {
  _id: string;
  _type: 'aboutUs';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  metadata?: Metadata;
  title: string;
  pageIntroText: string;
  heroImage?: BrandfolderImage;
  content?: ComposableContent;
};

export type BrandfolderImage = {
  _type: 'brandfolderImage';
  id?: string;
  url?: string;
  alt_text?: string;
  width?: number;
  height?: number;
};

export type Metadata = {
  _type: 'metadata';
  title?: string;
  description?: string;
  noIndex?: boolean;
  noFollow?: boolean;
};

export type YoutubeVideo = {
  _type: 'youtubeVideo';
  id: string;
  title?: string;
  description?: string;
  publishedAt?: string;
  thumbnails?: Array<string>;
};

export type Table = {
  _type: 'table';
  rows?: Array<
    {
      _key: string;
    } & TableRow
  >;
};

export type TableRow = {
  _type: 'tableRow';
  cells?: Array<string>;
};

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityFileAsset
  | Geopoint
  | CaseStudies
  | GoogleReviews
  | InfoTable
  | VideoEmbed
  | RawHtml
  | VerticalTabsItem
  | VerticalTabs
  | TwoSlotRichTextImage
  | TwoColumnRichTextAndForm
  | TwoColumnRichTextAndImage
  | TwoColumnRichText
  | TwoColumnList
  | TwoCardSection
  | Spacer
  | SocialMediaAccount
  | RailwayArches
  | PropertyDetails
  | PropertiesCta
  | PlainText
  | PdfDownload
  | BlogArticle
  | NewsArticle
  | NavigationItem
  | Navigation
  | LinkList
  | IndexHeroes
  | ImageRow
  | HorizontalContentCardSection
  | HorizontalContentCard
  | Hero
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata
  | Globals
  | GeneralInformation
  | GenericPage
  | LandingPage
  | TwoColumnEditorial
  | WhyUs
  | Homepage
  | ThreeCardSection
  | FullWidthImage
  | FourCardSection
  | FooterLink
  | Footer
  | FindYourSpace
  | FeaturedLocationsSub
  | FeaturedLocations
  | FeaturedProperties
  | ExistingCustomers
  | Errors
  | ContentCard
  | CtaRichText
  | RichText
  | ComposableContent
  | CaseStudy
  | Slug
  | BrandfolderPdf
  | AboutUs
  | BrandfolderImage
  | Metadata
  | YoutubeVideo
  | Table
  | TableRow;
export declare const internalGroqTypeReferenceTo: unique symbol;
